FROM huggingface/transformers-pytorch-deepspeed-nightly-gpu

RUN apt-get update -y

RUN pip -q install git+https://github.com/huggingface/transformers
RUN pip -q install git+https://github.com/endomorphosis/ipfs_transformers
RUN pip -q install accelerate>=0.12.0

WORKDIR /

COPY ./dolly_inference.py .